// Comprehensive IANA timezone data with flags, cities, and UTC offsets
// Generated from Intl.supportedValuesOf('timeZone') and enhanced with metadata

/* global module */

function getAllTimezones() {
  const timezones = [
    // UTC and GMT
    { value: 'UTC', name: 'Coordinated Universal Time', city: 'Global', flag: '🌐', offset: '+00:00', ianaTimezone: 'UTC', abbreviation: 'UTC' },
    { value: 'GMT', name: 'Greenwich Mean Time', city: 'London', flag: '🇬🇧', offset: '+00:00', ianaTimezone: 'GMT', abbreviation: 'GMT' },

    // Africa
    { value: 'Africa/Abidjan', name: 'West Africa Time', city: 'Abidjan', flag: '🇨🇮', offset: '+00:00', ianaTimezone: 'Africa/Abidjan', abbreviation: 'GMT' },
    { value: 'Africa/Accra', name: 'Ghana Mean Time', city: 'Accra', flag: '🇬🇭', offset: '+00:00', ianaTimezone: 'Africa/Accra', abbreviation: 'GMT' },
    { value: 'Africa/Addis_Ababa', name: 'East Africa Time', city: 'Addis Ababa', flag: '🇪🇹', offset: '+03:00', ianaTimezone: 'Africa/Addis_Ababa', abbreviation: 'EAT' },
    { value: 'Africa/Algiers', name: 'Central European Time', city: 'Algiers', flag: '🇩🇿', offset: '+01:00', ianaTimezone: 'Africa/Algiers', abbreviation: 'CET' },
    { value: 'Africa/Cairo', name: 'Eastern European Time', city: 'Cairo', flag: '🇪🇬', offset: '+02:00', ianaTimezone: 'Africa/Cairo', abbreviation: 'EET' },
    { value: 'Africa/Casablanca', name: 'Western European Time', city: 'Casablanca', flag: '🇲🇦', offset: '+01:00', ianaTimezone: 'Africa/Casablanca', abbreviation: 'WET' },
    { value: 'Africa/Ceuta', name: 'Central European Time', city: 'Ceuta', flag: '🇪🇸', offset: '+01:00', ianaTimezone: 'Africa/Ceuta', abbreviation: 'CET' },
    { value: 'Africa/El_Aaiun', name: 'Western European Time', city: 'El Aaiun', flag: '🇪🇭', offset: '+01:00', ianaTimezone: 'Africa/El_Aaiun', abbreviation: 'WET' },
    { value: 'Africa/Johannesburg', name: 'South Africa Standard Time', city: 'Johannesburg', flag: '🇿🇦', offset: '+02:00', ianaTimezone: 'Africa/Johannesburg', abbreviation: 'SAST' },
    { value: 'Africa/Juba', name: 'East Africa Time', city: 'Juba', flag: '🇸🇸', offset: '+03:00', ianaTimezone: 'Africa/Juba', abbreviation: 'EAT' },
    { value: 'Africa/Khartoum', name: 'Central Africa Time', city: 'Khartoum', flag: '🇸🇩', offset: '+02:00', ianaTimezone: 'Africa/Khartoum', abbreviation: 'CAT' },
    { value: 'Africa/Lagos', name: 'West Africa Time', city: 'Lagos', flag: '🇳🇬', offset: '+01:00', ianaTimezone: 'Africa/Lagos', abbreviation: 'WAT' },
    { value: 'Africa/Maputo', name: 'Central Africa Time', city: 'Maputo', flag: '🇲🇿', offset: '+02:00', ianaTimezone: 'Africa/Maputo', abbreviation: 'CAT' },
    { value: 'Africa/Monrovia', name: 'Greenwich Mean Time', city: 'Monrovia', flag: '🇱🇷', offset: '+00:00', ianaTimezone: 'Africa/Monrovia', abbreviation: 'GMT' },
    { value: 'Africa/Nairobi', name: 'East Africa Time', city: 'Nairobi', flag: '🇰🇪', offset: '+03:00', ianaTimezone: 'Africa/Nairobi', abbreviation: 'EAT' },
    { value: 'Africa/Ndjamena', name: 'West Africa Time', city: 'N\'Djamena', flag: '🇹🇩', offset: '+01:00', ianaTimezone: 'Africa/Ndjamena', abbreviation: 'WAT' },
    { value: 'Africa/Sao_Tome', name: 'Greenwich Mean Time', city: 'São Tomé', flag: '🇸🇹', offset: '+00:00', ianaTimezone: 'Africa/Sao_Tome', abbreviation: 'GMT' },
    { value: 'Africa/Tripoli', name: 'Eastern European Time', city: 'Tripoli', flag: '🇱🇾', offset: '+02:00', ianaTimezone: 'Africa/Tripoli', abbreviation: 'EET' },
    { value: 'Africa/Tunis', name: 'Central European Time', city: 'Tunis', flag: '🇹🇳', offset: '+01:00', ianaTimezone: 'Africa/Tunis', abbreviation: 'CET' },
    { value: 'Africa/Windhoek', name: 'Central Africa Time', city: 'Windhoek', flag: '🇳🇦', offset: '+02:00', ianaTimezone: 'Africa/Windhoek', abbreviation: 'CAT' },

    // America - North America
    { value: 'America/Adak', name: 'Hawaii-Aleutian Standard Time', city: 'Adak', flag: '🇺🇸', offset: '-10:00', ianaTimezone: 'America/Adak', abbreviation: 'HST' },
    { value: 'America/Anchorage', name: 'Alaska Standard Time', city: 'Anchorage', flag: '🇺🇸', offset: '-09:00', ianaTimezone: 'America/Anchorage', abbreviation: 'AKST' },
    { value: 'America/Anguilla', name: 'Atlantic Standard Time', city: 'The Valley', flag: '🇦🇮', offset: '-04:00', ianaTimezone: 'America/Anguilla', abbreviation: 'AST' },
    { value: 'America/Antigua', name: 'Atlantic Standard Time', city: 'St. John\'s', flag: '🇦🇬', offset: '-04:00', ianaTimezone: 'America/Antigua', abbreviation: 'AST' },
    { value: 'America/Araguaina', name: 'Brasília Time', city: 'Araguaína', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Araguaina', abbreviation: 'BRT' },
    { value: 'America/Argentina/Buenos_Aires', name: 'Argentina Time', city: 'Buenos Aires', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Buenos_Aires', abbreviation: 'ART' },
    { value: 'America/Argentina/Catamarca', name: 'Argentina Time', city: 'Catamarca', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Catamarca', abbreviation: 'ART' },
    { value: 'America/Argentina/Cordoba', name: 'Argentina Time', city: 'Córdoba', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Cordoba', abbreviation: 'ART' },
    { value: 'America/Argentina/Jujuy', name: 'Argentina Time', city: 'Jujuy', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Jujuy', abbreviation: 'ART' },
    { value: 'America/Argentina/La_Rioja', name: 'Argentina Time', city: 'La Rioja', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/La_Rioja', abbreviation: 'ART' },
    { value: 'America/Argentina/Mendoza', name: 'Argentina Time', city: 'Mendoza', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Mendoza', abbreviation: 'ART' },
    { value: 'America/Argentina/Rio_Gallegos', name: 'Argentina Time', city: 'Río Gallegos', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Rio_Gallegos', abbreviation: 'ART' },
    { value: 'America/Argentina/Salta', name: 'Argentina Time', city: 'Salta', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Salta', abbreviation: 'ART' },
    { value: 'America/Argentina/San_Juan', name: 'Argentina Time', city: 'San Juan', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/San_Juan', abbreviation: 'ART' },
    { value: 'America/Argentina/San_Luis', name: 'Argentina Time', city: 'San Luis', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/San_Luis', abbreviation: 'ART' },
    { value: 'America/Argentina/Tucuman', name: 'Argentina Time', city: 'Tucumán', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Tucuman', abbreviation: 'ART' },
    { value: 'America/Argentina/Ushuaia', name: 'Argentina Time', city: 'Ushuaia', flag: '🇦🇷', offset: '-03:00', ianaTimezone: 'America/Argentina/Ushuaia', abbreviation: 'ART' },
    { value: 'America/Aruba', name: 'Atlantic Standard Time', city: 'Oranjestad', flag: '🇦🇼', offset: '-04:00', ianaTimezone: 'America/Aruba', abbreviation: 'AST' },
    { value: 'America/Asuncion', name: 'Paraguay Time', city: 'Asunción', flag: '🇵🇾', offset: '-03:00', ianaTimezone: 'America/Asuncion', abbreviation: 'PYT' },
    { value: 'America/Atikokan', name: 'Eastern Standard Time', city: 'Atikokan', flag: '🇨🇦', offset: '-05:00', ianaTimezone: 'America/Atikokan', abbreviation: 'EST' },
    { value: 'America/Bahia', name: 'Brasília Time', city: 'Salvador', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Bahia', abbreviation: 'BRT' },
    { value: 'America/Bahia_Banderas', name: 'Central Standard Time', city: 'Bahía de Banderas', flag: '🇲🇽', offset: '-06:00', ianaTimezone: 'America/Bahia_Banderas', abbreviation: 'CST' },
    { value: 'America/Barbados', name: 'Atlantic Standard Time', city: 'Bridgetown', flag: '🇧🇧', offset: '-04:00', ianaTimezone: 'America/Barbados', abbreviation: 'AST' },
    { value: 'America/Belem', name: 'Brasília Time', city: 'Belém', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Belem', abbreviation: 'BRT' },
    { value: 'America/Belize', name: 'Central Standard Time', city: 'Belize City', flag: '🇧🇿', offset: '-06:00', ianaTimezone: 'America/Belize', abbreviation: 'CST' },
    { value: 'America/Blanc-Sablon', name: 'Atlantic Standard Time', city: 'Blanc-Sablon', flag: '🇨🇦', offset: '-04:00', ianaTimezone: 'America/Blanc-Sablon', abbreviation: 'AST' },
    { value: 'America/Boa_Vista', name: 'Amazon Time', city: 'Boa Vista', flag: '🇧🇷', offset: '-04:00', ianaTimezone: 'America/Boa_Vista', abbreviation: 'AMT' },
    { value: 'America/Bogota', name: 'Colombia Time', city: 'Bogotá', flag: '🇨🇴', offset: '-05:00', ianaTimezone: 'America/Bogota', abbreviation: 'COT' },
    { value: 'America/Boise', name: 'Mountain Standard Time', city: 'Boise', flag: '🇺🇸', offset: '-07:00', ianaTimezone: 'America/Boise', abbreviation: 'MST' },
    { value: 'America/Cambridge_Bay', name: 'Mountain Standard Time', city: 'Cambridge Bay', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Cambridge_Bay', abbreviation: 'MST' },
    { value: 'America/Campo_Grande', name: 'Amazon Time', city: 'Campo Grande', flag: '🇧🇷', offset: '-04:00', ianaTimezone: 'America/Campo_Grande', abbreviation: 'AMT' },
    { value: 'America/Cancun', name: 'Eastern Standard Time', city: 'Cancún', flag: '🇲🇽', offset: '-05:00', ianaTimezone: 'America/Cancun', abbreviation: 'EST' },
    { value: 'America/Caracas', name: 'Venezuela Time', city: 'Caracas', flag: '🇻🇪', offset: '-04:00', ianaTimezone: 'America/Caracas', abbreviation: 'VET' },
    { value: 'America/Cayenne', name: 'French Guiana Time', city: 'Cayenne', flag: '🇬🇫', offset: '-03:00', ianaTimezone: 'America/Cayenne', abbreviation: 'GFT' },
    { value: 'America/Cayman', name: 'Eastern Standard Time', city: 'George Town', flag: '🇰🇾', offset: '-05:00', ianaTimezone: 'America/Cayman', abbreviation: 'EST' },
    { value: 'America/Chicago', name: 'Central Standard Time', city: 'Chicago', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/Chicago', abbreviation: 'CST' },
    { value: 'America/Chihuahua', name: 'Mountain Standard Time', city: 'Chihuahua', flag: '🇲🇽', offset: '-07:00', ianaTimezone: 'America/Chihuahua', abbreviation: 'MST' },
    { value: 'America/Costa_Rica', name: 'Central Standard Time', city: 'San José', flag: '🇨🇷', offset: '-06:00', ianaTimezone: 'America/Costa_Rica', abbreviation: 'CST' },
    { value: 'America/Creston', name: 'Mountain Standard Time', city: 'Creston', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Creston', abbreviation: 'MST' },
    { value: 'America/Cuiaba', name: 'Amazon Time', city: 'Cuiabá', flag: '🇧🇷', offset: '-04:00', ianaTimezone: 'America/Cuiaba', abbreviation: 'AMT' },
    { value: 'America/Curacao', name: 'Atlantic Standard Time', city: 'Willemstad', flag: '🇨🇼', offset: '-04:00', ianaTimezone: 'America/Curacao', abbreviation: 'AST' },
    { value: 'America/Danmarkshavn', name: 'Greenwich Mean Time', city: 'Danmarkshavn', flag: '🇬🇱', offset: '+00:00', ianaTimezone: 'America/Danmarkshavn', abbreviation: 'GMT' },
    { value: 'America/Dawson', name: 'Pacific Standard Time', city: 'Dawson', flag: '🇨🇦', offset: '-08:00', ianaTimezone: 'America/Dawson', abbreviation: 'PST' },
    { value: 'America/Dawson_Creek', name: 'Mountain Standard Time', city: 'Dawson Creek', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Dawson_Creek', abbreviation: 'MST' },
    { value: 'America/Denver', name: 'Mountain Standard Time', city: 'Denver', flag: '🇺🇸', offset: '-07:00', ianaTimezone: 'America/Denver', abbreviation: 'MST' },
    { value: 'America/Detroit', name: 'Eastern Standard Time', city: 'Detroit', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Detroit', abbreviation: 'EST' },
    { value: 'America/Dominica', name: 'Atlantic Standard Time', city: 'Roseau', flag: '🇩🇲', offset: '-04:00', ianaTimezone: 'America/Dominica', abbreviation: 'AST' },
    { value: 'America/Edmonton', name: 'Mountain Standard Time', city: 'Edmonton', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Edmonton', abbreviation: 'MST' },
    { value: 'America/Eirunepe', name: 'Acre Time', city: 'Eirunepé', flag: '🇧🇷', offset: '-05:00', ianaTimezone: 'America/Eirunepe', abbreviation: 'ACT' },
    { value: 'America/El_Salvador', name: 'Central Standard Time', city: 'San Salvador', flag: '🇸🇻', offset: '-06:00', ianaTimezone: 'America/El_Salvador', abbreviation: 'CST' },
    { value: 'America/Fort_Nelson', name: 'Mountain Standard Time', city: 'Fort Nelson', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Fort_Nelson', abbreviation: 'MST' },
    { value: 'America/Fortaleza', name: 'Brasília Time', city: 'Fortaleza', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Fortaleza', abbreviation: 'BRT' },
    { value: 'America/Glace_Bay', name: 'Atlantic Standard Time', city: 'Glace Bay', flag: '🇨🇦', offset: '-04:00', ianaTimezone: 'America/Glace_Bay', abbreviation: 'AST' },
    { value: 'America/Goose_Bay', name: 'Atlantic Standard Time', city: 'Happy Valley-Goose Bay', flag: '🇨🇦', offset: '-04:00', ianaTimezone: 'America/Goose_Bay', abbreviation: 'AST' },
    { value: 'America/Grand_Turk', name: 'Eastern Standard Time', city: 'Cockburn Town', flag: '🇹🇨', offset: '-05:00', ianaTimezone: 'America/Grand_Turk', abbreviation: 'EST' },
    { value: 'America/Grenada', name: 'Atlantic Standard Time', city: 'St. George\'s', flag: '🇬🇩', offset: '-04:00', ianaTimezone: 'America/Grenada', abbreviation: 'AST' },
    { value: 'America/Guadeloupe', name: 'Atlantic Standard Time', city: 'Basse-Terre', flag: '🇬🇵', offset: '-04:00', ianaTimezone: 'America/Guadeloupe', abbreviation: 'AST' },
    { value: 'America/Guatemala', name: 'Central Standard Time', city: 'Guatemala City', flag: '🇬🇹', offset: '-06:00', ianaTimezone: 'America/Guatemala', abbreviation: 'CST' },
    { value: 'America/Guayaquil', name: 'Ecuador Time', city: 'Guayaquil', flag: '🇪🇨', offset: '-05:00', ianaTimezone: 'America/Guayaquil', abbreviation: 'ECT' },
    { value: 'America/Guyana', name: 'Guyana Time', city: 'Georgetown', flag: '🇬🇾', offset: '-04:00', ianaTimezone: 'America/Guyana', abbreviation: 'GYT' },
    { value: 'America/Halifax', name: 'Atlantic Standard Time', city: 'Halifax', flag: '🇨🇦', offset: '-04:00', ianaTimezone: 'America/Halifax', abbreviation: 'AST' },
    { value: 'America/Havana', name: 'Cuba Standard Time', city: 'Havana', flag: '🇨🇺', offset: '-05:00', ianaTimezone: 'America/Havana', abbreviation: 'CST' },
    { value: 'America/Hermosillo', name: 'Mountain Standard Time', city: 'Hermosillo', flag: '🇲🇽', offset: '-07:00', ianaTimezone: 'America/Hermosillo', abbreviation: 'MST' },
    { value: 'America/Indiana/Indianapolis', name: 'Eastern Standard Time', city: 'Indianapolis', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Indiana/Indianapolis', abbreviation: 'EST' },
    { value: 'America/Indiana/Knox', name: 'Central Standard Time', city: 'Knox', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/Indiana/Knox', abbreviation: 'CST' },
    { value: 'America/Indiana/Marengo', name: 'Eastern Standard Time', city: 'Marengo', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Indiana/Marengo', abbreviation: 'EST' },
    { value: 'America/Indiana/Petersburg', name: 'Eastern Standard Time', city: 'Petersburg', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Indiana/Petersburg', abbreviation: 'EST' },
    { value: 'America/Indiana/Tell_City', name: 'Central Standard Time', city: 'Tell City', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/Indiana/Tell_City', abbreviation: 'CST' },
    { value: 'America/Indiana/Vevay', name: 'Eastern Standard Time', city: 'Vevay', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Indiana/Vevay', abbreviation: 'EST' },
    { value: 'America/Indiana/Vincennes', name: 'Eastern Standard Time', city: 'Vincennes', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Indiana/Vincennes', abbreviation: 'EST' },
    { value: 'America/Indiana/Winamac', name: 'Eastern Standard Time', city: 'Winamac', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Indiana/Winamac', abbreviation: 'EST' },
    { value: 'America/Inuvik', name: 'Mountain Standard Time', city: 'Inuvik', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Inuvik', abbreviation: 'MST' },
    { value: 'America/Iqaluit', name: 'Eastern Standard Time', city: 'Iqaluit', flag: '🇨🇦', offset: '-05:00', ianaTimezone: 'America/Iqaluit', abbreviation: 'EST' },
    { value: 'America/Jamaica', name: 'Eastern Standard Time', city: 'Kingston', flag: '🇯🇲', offset: '-05:00', ianaTimezone: 'America/Jamaica', abbreviation: 'EST' },
    { value: 'America/Juneau', name: 'Alaska Standard Time', city: 'Juneau', flag: '🇺🇸', offset: '-09:00', ianaTimezone: 'America/Juneau', abbreviation: 'AKST' },
    { value: 'America/Kentucky/Louisville', name: 'Eastern Standard Time', city: 'Louisville', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Kentucky/Louisville', abbreviation: 'EST' },
    { value: 'America/Kentucky/Monticello', name: 'Eastern Standard Time', city: 'Monticello', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/Kentucky/Monticello', abbreviation: 'EST' },
    { value: 'America/Kralendijk', name: 'Atlantic Standard Time', city: 'Kralendijk', flag: '🇧🇶', offset: '-04:00', ianaTimezone: 'America/Kralendijk', abbreviation: 'AST' },
    { value: 'America/La_Paz', name: 'Bolivia Time', city: 'La Paz', flag: '🇧🇴', offset: '-04:00', ianaTimezone: 'America/La_Paz', abbreviation: 'BOT' },
    { value: 'America/Lima', name: 'Peru Time', city: 'Lima', flag: '🇵🇪', offset: '-05:00', ianaTimezone: 'America/Lima', abbreviation: 'PET' },
    { value: 'America/Los_Angeles', name: 'Pacific Standard Time', city: 'Los Angeles', flag: '🇺🇸', offset: '-08:00', ianaTimezone: 'America/Los_Angeles', abbreviation: 'PST' },
    { value: 'America/Lower_Princes', name: 'Atlantic Standard Time', city: 'Lower Prince\'s Quarter', flag: '🇸🇽', offset: '-04:00', ianaTimezone: 'America/Lower_Princes', abbreviation: 'AST' },
    { value: 'America/Maceio', name: 'Brasília Time', city: 'Maceió', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Maceio', abbreviation: 'BRT' },
    { value: 'America/Managua', name: 'Central Standard Time', city: 'Managua', flag: '🇳🇮', offset: '-06:00', ianaTimezone: 'America/Managua', abbreviation: 'CST' },
    { value: 'America/Manaus', name: 'Amazon Time', city: 'Manaus', flag: '🇧🇷', offset: '-04:00', ianaTimezone: 'America/Manaus', abbreviation: 'AMT' },
    { value: 'America/Marigot', name: 'Atlantic Standard Time', city: 'Marigot', flag: '🇲🇫', offset: '-04:00', ianaTimezone: 'America/Marigot', abbreviation: 'AST' },
    { value: 'America/Martinique', name: 'Atlantic Standard Time', city: 'Fort-de-France', flag: '🇲🇶', offset: '-04:00', ianaTimezone: 'America/Martinique', abbreviation: 'AST' },
    { value: 'America/Matamoros', name: 'Central Standard Time', city: 'Matamoros', flag: '🇲🇽', offset: '-06:00', ianaTimezone: 'America/Matamoros', abbreviation: 'CST' },
    { value: 'America/Mazatlan', name: 'Mountain Standard Time', city: 'Mazatlán', flag: '🇲🇽', offset: '-07:00', ianaTimezone: 'America/Mazatlan', abbreviation: 'MST' },
    { value: 'America/Menominee', name: 'Central Standard Time', city: 'Menominee', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/Menominee', abbreviation: 'CST' },
    { value: 'America/Merida', name: 'Central Standard Time', city: 'Mérida', flag: '🇲🇽', offset: '-06:00', ianaTimezone: 'America/Merida', abbreviation: 'CST' },
    { value: 'America/Metlakatla', name: 'Alaska Standard Time', city: 'Metlakatla', flag: '🇺🇸', offset: '-09:00', ianaTimezone: 'America/Metlakatla', abbreviation: 'AKST' },
    { value: 'America/Mexico_City', name: 'Central Standard Time', city: 'Mexico City', flag: '🇲🇽', offset: '-06:00', ianaTimezone: 'America/Mexico_City', abbreviation: 'CST' },
    { value: 'America/Miquelon', name: 'St. Pierre & Miquelon Standard Time', city: 'Saint-Pierre', flag: '🇵🇲', offset: '-03:00', ianaTimezone: 'America/Miquelon', abbreviation: 'PMST' },
    { value: 'America/Moncton', name: 'Atlantic Standard Time', city: 'Moncton', flag: '🇨🇦', offset: '-04:00', ianaTimezone: 'America/Moncton', abbreviation: 'AST' },
    { value: 'America/Monterrey', name: 'Central Standard Time', city: 'Monterrey', flag: '🇲🇽', offset: '-06:00', ianaTimezone: 'America/Monterrey', abbreviation: 'CST' },
    { value: 'America/Montevideo', name: 'Uruguay Standard Time', city: 'Montevideo', flag: '🇺🇾', offset: '-03:00', ianaTimezone: 'America/Montevideo', abbreviation: 'UYT' },
    { value: 'America/Montserrat', name: 'Atlantic Standard Time', city: 'Plymouth', flag: '🇲🇸', offset: '-04:00', ianaTimezone: 'America/Montserrat', abbreviation: 'AST' },
    { value: 'America/Nassau', name: 'Eastern Standard Time', city: 'Nassau', flag: '🇧🇸', offset: '-05:00', ianaTimezone: 'America/Nassau', abbreviation: 'EST' },
    { value: 'America/New_York', name: 'Eastern Standard Time', city: 'New York', flag: '🇺🇸', offset: '-05:00', ianaTimezone: 'America/New_York', abbreviation: 'EST' },
    { value: 'America/Nipigon', name: 'Eastern Standard Time', city: 'Nipigon', flag: '🇨🇦', offset: '-05:00', ianaTimezone: 'America/Nipigon', abbreviation: 'EST' },
    { value: 'America/Nome', name: 'Alaska Standard Time', city: 'Nome', flag: '🇺🇸', offset: '-09:00', ianaTimezone: 'America/Nome', abbreviation: 'AKST' },
    { value: 'America/Noronha', name: 'Fernando de Noronha Time', city: 'Fernando de Noronha', flag: '🇧🇷', offset: '-02:00', ianaTimezone: 'America/Noronha', abbreviation: 'FNT' },
    { value: 'America/North_Dakota/Beulah', name: 'Central Standard Time', city: 'Beulah', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/North_Dakota/Beulah', abbreviation: 'CST' },
    { value: 'America/North_Dakota/Center', name: 'Central Standard Time', city: 'Center', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/North_Dakota/Center', abbreviation: 'CST' },
    { value: 'America/North_Dakota/New_Salem', name: 'Central Standard Time', city: 'New Salem', flag: '🇺🇸', offset: '-06:00', ianaTimezone: 'America/North_Dakota/New_Salem', abbreviation: 'CST' },
    { value: 'America/Nuuk', name: 'West Greenland Time', city: 'Nuuk', flag: '🇬🇱', offset: '-03:00', ianaTimezone: 'America/Nuuk', abbreviation: 'WGT' },
    { value: 'America/Ojinaga', name: 'Mountain Standard Time', city: 'Ojinaga', flag: '🇲🇽', offset: '-07:00', ianaTimezone: 'America/Ojinaga', abbreviation: 'MST' },
    { value: 'America/Panama', name: 'Eastern Standard Time', city: 'Panama City', flag: '🇵🇦', offset: '-05:00', ianaTimezone: 'America/Panama', abbreviation: 'EST' },
    { value: 'America/Pangnirtung', name: 'Eastern Standard Time', city: 'Pangnirtung', flag: '🇨🇦', offset: '-05:00', ianaTimezone: 'America/Pangnirtung', abbreviation: 'EST' },
    { value: 'America/Paramaribo', name: 'Suriname Time', city: 'Paramaribo', flag: '🇸🇷', offset: '-03:00', ianaTimezone: 'America/Paramaribo', abbreviation: 'SRT' },
    { value: 'America/Phoenix', name: 'Mountain Standard Time', city: 'Phoenix', flag: '🇺🇸', offset: '-07:00', ianaTimezone: 'America/Phoenix', abbreviation: 'MST' },
    { value: 'America/Port-au-Prince', name: 'Eastern Standard Time', city: 'Port-au-Prince', flag: '🇭🇹', offset: '-05:00', ianaTimezone: 'America/Port-au-Prince', abbreviation: 'EST' },
    { value: 'America/Port_of_Spain', name: 'Atlantic Standard Time', city: 'Port of Spain', flag: '🇹🇹', offset: '-04:00', ianaTimezone: 'America/Port_of_Spain', abbreviation: 'AST' },
    { value: 'America/Porto_Velho', name: 'Amazon Time', city: 'Porto Velho', flag: '🇧🇷', offset: '-04:00', ianaTimezone: 'America/Porto_Velho', abbreviation: 'AMT' },
    { value: 'America/Puerto_Rico', name: 'Atlantic Standard Time', city: 'San Juan', flag: '🇵🇷', offset: '-04:00', ianaTimezone: 'America/Puerto_Rico', abbreviation: 'AST' },
    { value: 'America/Punta_Arenas', name: 'Chile Standard Time', city: 'Punta Arenas', flag: '🇨🇱', offset: '-03:00', ianaTimezone: 'America/Punta_Arenas', abbreviation: 'CLT' },
    { value: 'America/Rainy_River', name: 'Central Standard Time', city: 'Rainy River', flag: '🇨🇦', offset: '-06:00', ianaTimezone: 'America/Rainy_River', abbreviation: 'CST' },
    { value: 'America/Rankin_Inlet', name: 'Central Standard Time', city: 'Rankin Inlet', flag: '🇨🇦', offset: '-06:00', ianaTimezone: 'America/Rankin_Inlet', abbreviation: 'CST' },
    { value: 'America/Recife', name: 'Brasília Time', city: 'Recife', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Recife', abbreviation: 'BRT' },
    { value: 'America/Regina', name: 'Central Standard Time', city: 'Regina', flag: '🇨🇦', offset: '-06:00', ianaTimezone: 'America/Regina', abbreviation: 'CST' },
    { value: 'America/Resolute', name: 'Central Standard Time', city: 'Resolute', flag: '🇨🇦', offset: '-06:00', ianaTimezone: 'America/Resolute', abbreviation: 'CST' },
    { value: 'America/Rio_Branco', name: 'Acre Time', city: 'Rio Branco', flag: '🇧🇷', offset: '-05:00', ianaTimezone: 'America/Rio_Branco', abbreviation: 'ACT' },
    { value: 'America/Santarem', name: 'Brasília Time', city: 'Santarém', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Santarem', abbreviation: 'BRT' },
    { value: 'America/Santiago', name: 'Chile Standard Time', city: 'Santiago', flag: '🇨🇱', offset: '-04:00', ianaTimezone: 'America/Santiago', abbreviation: 'CLT' },
    { value: 'America/Santo_Domingo', name: 'Atlantic Standard Time', city: 'Santo Domingo', flag: '🇩🇴', offset: '-04:00', ianaTimezone: 'America/Santo_Domingo', abbreviation: 'AST' },
    { value: 'America/Sao_Paulo', name: 'Brasília Time', city: 'São Paulo', flag: '🇧🇷', offset: '-03:00', ianaTimezone: 'America/Sao_Paulo', abbreviation: 'BRT' },
    { value: 'America/Scoresbysund', name: 'East Greenland Time', city: 'Scoresbysund', flag: '🇬🇱', offset: '-01:00', ianaTimezone: 'America/Scoresbysund', abbreviation: 'EGT' },
    { value: 'America/Sitka', name: 'Alaska Standard Time', city: 'Sitka', flag: '🇺🇸', offset: '-09:00', ianaTimezone: 'America/Sitka', abbreviation: 'AKST' },
    { value: 'America/St_Barthelemy', name: 'Atlantic Standard Time', city: 'Gustavia', flag: '🇧🇱', offset: '-04:00', ianaTimezone: 'America/St_Barthelemy', abbreviation: 'AST' },
    { value: 'America/St_Johns', name: 'Newfoundland Standard Time', city: 'St. John\'s', flag: '🇨🇦', offset: '-03:30', ianaTimezone: 'America/St_Johns', abbreviation: 'NST' },
    { value: 'America/St_Kitts', name: 'Atlantic Standard Time', city: 'Basseterre', flag: '🇰🇳', offset: '-04:00', ianaTimezone: 'America/St_Kitts', abbreviation: 'AST' },
    { value: 'America/St_Lucia', name: 'Atlantic Standard Time', city: 'Castries', flag: '🇱🇨', offset: '-04:00', ianaTimezone: 'America/St_Lucia', abbreviation: 'AST' },
    { value: 'America/St_Thomas', name: 'Atlantic Standard Time', city: 'Charlotte Amalie', flag: '🇻🇮', offset: '-04:00', ianaTimezone: 'America/St_Thomas', abbreviation: 'AST' },
    { value: 'America/St_Vincent', name: 'Atlantic Standard Time', city: 'Kingstown', flag: '🇻🇨', offset: '-04:00', ianaTimezone: 'America/St_Vincent', abbreviation: 'AST' },
    { value: 'America/Swift_Current', name: 'Central Standard Time', city: 'Swift Current', flag: '🇨🇦', offset: '-06:00', ianaTimezone: 'America/Swift_Current', abbreviation: 'CST' },
    { value: 'America/Tegucigalpa', name: 'Central Standard Time', city: 'Tegucigalpa', flag: '🇭🇳', offset: '-06:00', ianaTimezone: 'America/Tegucigalpa', abbreviation: 'CST' },
    { value: 'America/Thule', name: 'Atlantic Standard Time', city: 'Thule', flag: '🇬🇱', offset: '-04:00', ianaTimezone: 'America/Thule', abbreviation: 'AST' },
    { value: 'America/Thunder_Bay', name: 'Eastern Standard Time', city: 'Thunder Bay', flag: '🇨🇦', offset: '-05:00', ianaTimezone: 'America/Thunder_Bay', abbreviation: 'EST' },
    { value: 'America/Tijuana', name: 'Pacific Standard Time', city: 'Tijuana', flag: '🇲🇽', offset: '-08:00', ianaTimezone: 'America/Tijuana', abbreviation: 'PST' },
    { value: 'America/Toronto', name: 'Eastern Standard Time', city: 'Toronto', flag: '🇨🇦', offset: '-05:00', ianaTimezone: 'America/Toronto', abbreviation: 'EST' },
    { value: 'America/Tortola', name: 'Atlantic Standard Time', city: 'Road Town', flag: '🇻🇬', offset: '-04:00', ianaTimezone: 'America/Tortola', abbreviation: 'AST' },
    { value: 'America/Vancouver', name: 'Pacific Standard Time', city: 'Vancouver', flag: '🇨🇦', offset: '-08:00', ianaTimezone: 'America/Vancouver', abbreviation: 'PST' },
    { value: 'America/Whitehorse', name: 'Pacific Standard Time', city: 'Whitehorse', flag: '🇨🇦', offset: '-08:00', ianaTimezone: 'America/Whitehorse', abbreviation: 'PST' },
    { value: 'America/Winnipeg', name: 'Central Standard Time', city: 'Winnipeg', flag: '🇨🇦', offset: '-06:00', ianaTimezone: 'America/Winnipeg', abbreviation: 'CST' },
    { value: 'America/Yakutat', name: 'Alaska Standard Time', city: 'Yakutat', flag: '🇺🇸', offset: '-09:00', ianaTimezone: 'America/Yakutat', abbreviation: 'AKST' },
    { value: 'America/Yellowknife', name: 'Mountain Standard Time', city: 'Yellowknife', flag: '🇨🇦', offset: '-07:00', ianaTimezone: 'America/Yellowknife', abbreviation: 'MST' },

    // Antarctica
    { value: 'Antarctica/Casey', name: 'Antarctica Time', city: 'Casey Station', flag: '🇦🇶', offset: '+11:00', ianaTimezone: 'Antarctica/Casey', abbreviation: 'ART' },
    { value: 'Antarctica/Davis', name: 'Antarctica Time', city: 'Davis Station', flag: '🇦🇶', offset: '+07:00', ianaTimezone: 'Antarctica/Davis', abbreviation: 'ART' },
    { value: 'Antarctica/DumontDUrville', name: 'Antarctica Time', city: 'Dumont d\'Urville Station', flag: '🇦🇶', offset: '+10:00', ianaTimezone: 'Antarctica/DumontDUrville', abbreviation: 'ART' },
    { value: 'Antarctica/Macquarie', name: 'Antarctica Time', city: 'Macquarie Island', flag: '🇦🇶', offset: '+11:00', ianaTimezone: 'Antarctica/Macquarie', abbreviation: 'ART' },
    { value: 'Antarctica/Mawson', name: 'Antarctica Time', city: 'Mawson Station', flag: '🇦🇶', offset: '+05:00', ianaTimezone: 'Antarctica/Mawson', abbreviation: 'ART' },
    { value: 'Antarctica/McMurdo', name: 'Antarctica Time', city: 'McMurdo Station', flag: '🇦🇶', offset: '+12:00', ianaTimezone: 'Antarctica/McMurdo', abbreviation: 'ART' },
    { value: 'Antarctica/Palmer', name: 'Antarctica Time', city: 'Palmer Station', flag: '🇦🇶', offset: '-03:00', ianaTimezone: 'Antarctica/Palmer', abbreviation: 'ART' },
    { value: 'Antarctica/Rothera', name: 'Antarctica Time', city: 'Rothera Station', flag: '🇦🇶', offset: '-03:00', ianaTimezone: 'Antarctica/Rothera', abbreviation: 'ART' },
    { value: 'Antarctica/Syowa', name: 'Antarctica Time', city: 'Syowa Station', flag: '🇦🇶', offset: '+03:00', ianaTimezone: 'Antarctica/Syowa', abbreviation: 'ART' },
    { value: 'Antarctica/Troll', name: 'Antarctica Time', city: 'Troll Station', flag: '🇦🇶', offset: '+00:00', ianaTimezone: 'Antarctica/Troll', abbreviation: 'ART' },
    { value: 'Antarctica/Vostok', name: 'Antarctica Time', city: 'Vostok Station', flag: '🇦🇶', offset: '+06:00', ianaTimezone: 'Antarctica/Vostok', abbreviation: 'ART' },

    // Arctic
    { value: 'Arctic/Longyearbyen', name: 'Central European Time', city: 'Longyearbyen', flag: '🇸🇯', offset: '+01:00', ianaTimezone: 'Arctic/Longyearbyen', abbreviation: 'CET' },

    // Asia
    { value: 'Asia/Aden', name: 'Arabia Standard Time', city: 'Aden', flag: '🇾🇪', offset: '+03:00', ianaTimezone: 'Asia/Aden', abbreviation: 'AST' },
    { value: 'Asia/Almaty', name: 'Almaty Time', city: 'Almaty', flag: '🇰🇿', offset: '+06:00', ianaTimezone: 'Asia/Almaty', abbreviation: 'ALMT' },
    { value: 'Asia/Amman', name: 'Eastern European Time', city: 'Amman', flag: '🇯🇴', offset: '+02:00', ianaTimezone: 'Asia/Amman', abbreviation: 'EET' },
    { value: 'Asia/Anadyr', name: 'Anadyr Time', city: 'Anadyr', flag: '🇷🇺', offset: '+12:00', ianaTimezone: 'Asia/Anadyr', abbreviation: 'ANAT' },
    { value: 'Asia/Aqtau', name: 'Aqtau Time', city: 'Aqtau', flag: '🇰🇿', offset: '+05:00', ianaTimezone: 'Asia/Aqtau', abbreviation: 'AQTT' },
    { value: 'Asia/Aqtobe', name: 'Aqtobe Time', city: 'Aqtobe', flag: '🇰🇿', offset: '+05:00', ianaTimezone: 'Asia/Aqtobe', abbreviation: 'AQTT' },
    { value: 'Asia/Ashgabat', name: 'Turkmenistan Time', city: 'Ashgabat', flag: '🇹🇲', offset: '+05:00', ianaTimezone: 'Asia/Ashgabat', abbreviation: 'TMT' },
    { value: 'Asia/Atyrau', name: 'West Kazakhstan Time', city: 'Atyrau', flag: '🇰🇿', offset: '+05:00', ianaTimezone: 'Asia/Atyrau', abbreviation: 'WKT' },
    { value: 'Asia/Baghdad', name: 'Arabia Standard Time', city: 'Baghdad', flag: '🇮🇶', offset: '+03:00', ianaTimezone: 'Asia/Baghdad', abbreviation: 'AST' },
    { value: 'Asia/Bahrain', name: 'Arabia Standard Time', city: 'Manama', flag: '🇧🇭', offset: '+03:00', ianaTimezone: 'Asia/Bahrain', abbreviation: 'AST' },
    { value: 'Asia/Baku', name: 'Azerbaijan Time', city: 'Baku', flag: '🇦🇿', offset: '+04:00', ianaTimezone: 'Asia/Baku', abbreviation: 'AZT' },
    { value: 'Asia/Bangkok', name: 'Indochina Time', city: 'Bangkok', flag: '🇹🇭', offset: '+07:00', ianaTimezone: 'Asia/Bangkok', abbreviation: 'ICT' },
    { value: 'Asia/Barnaul', name: 'Barnaul Time', city: 'Barnaul', flag: '🇷🇺', offset: '+07:00', ianaTimezone: 'Asia/Barnaul', abbreviation: 'BAR' },
    { value: 'Asia/Beirut', name: 'Eastern European Time', city: 'Beirut', flag: '🇱🇧', offset: '+02:00', ianaTimezone: 'Asia/Beirut', abbreviation: 'EET' },
    { value: 'Asia/Bishkek', name: 'Kyrgyzstan Time', city: 'Bishkek', flag: '🇰🇬', offset: '+06:00', ianaTimezone: 'Asia/Bishkek', abbreviation: 'KGT' },
    { value: 'Asia/Brunei', name: 'Brunei Darussalam Time', city: 'Bandar Seri Begawan', flag: '🇧🇳', offset: '+08:00', ianaTimezone: 'Asia/Brunei', abbreviation: 'BNT' },
    { value: 'Asia/Chita', name: 'Yakutsk Time', city: 'Chita', flag: '🇷🇺', offset: '+09:00', ianaTimezone: 'Asia/Chita', abbreviation: 'YAKT' },
    { value: 'Asia/Choibalsan', name: 'Choibalsan Standard Time', city: 'Choibalsan', flag: '🇲🇳', offset: '+08:00', ianaTimezone: 'Asia/Choibalsan', abbreviation: 'CHOT' },
    { value: 'Asia/Colombo', name: 'India Standard Time', city: 'Colombo', flag: '🇱🇰', offset: '+05:30', ianaTimezone: 'Asia/Colombo', abbreviation: 'IST' },
    { value: 'Asia/Damascus', name: 'Eastern European Time', city: 'Damascus', flag: '🇸🇾', offset: '+02:00', ianaTimezone: 'Asia/Damascus', abbreviation: 'EET' },
    { value: 'Asia/Dhaka', name: 'Bangladesh Standard Time', city: 'Dhaka', flag: '🇧🇩', offset: '+06:00', ianaTimezone: 'Asia/Dhaka', abbreviation: 'BST' },
    { value: 'Asia/Dili', name: 'Timor-Leste Time', city: 'Dili', flag: '🇹🇱', offset: '+09:00', ianaTimezone: 'Asia/Dili', abbreviation: 'TLT' },
    { value: 'Asia/Dubai', name: 'Gulf Standard Time', city: 'Dubai', flag: '🇦🇪', offset: '+04:00', ianaTimezone: 'Asia/Dubai', abbreviation: 'GST' },
    { value: 'Asia/Dushanbe', name: 'Tajikistan Time', city: 'Dushanbe', flag: '🇹🇯', offset: '+05:00', ianaTimezone: 'Asia/Dushanbe', abbreviation: 'TJT' },
    { value: 'Asia/Famagusta', name: 'Eastern European Time', city: 'Famagusta', flag: '🇨🇾', offset: '+02:00', ianaTimezone: 'Asia/Famagusta', abbreviation: 'EET' },
    { value: 'Asia/Gaza', name: 'Eastern European Time', city: 'Gaza', flag: '🇵🇸', offset: '+02:00', ianaTimezone: 'Asia/Gaza', abbreviation: 'EET' },
    { value: 'Asia/Hebron', name: 'Eastern European Time', city: 'Hebron', flag: '🇵🇸', offset: '+02:00', ianaTimezone: 'Asia/Hebron', abbreviation: 'EET' },
    { value: 'Asia/Ho_Chi_Minh', name: 'Indochina Time', city: 'Ho Chi Minh City', flag: '🇻🇳', offset: '+07:00', ianaTimezone: 'Asia/Ho_Chi_Minh', abbreviation: 'ICT' },
    { value: 'Asia/Hong_Kong', name: 'Hong Kong Time', city: 'Hong Kong', flag: '🇭🇰', offset: '+08:00', ianaTimezone: 'Asia/Hong_Kong', abbreviation: 'HKT' },
    { value: 'Asia/Hovd', name: 'Hovd Standard Time', city: 'Hovd', flag: '🇲🇳', offset: '+07:00', ianaTimezone: 'Asia/Hovd', abbreviation: 'HOVT' },
    { value: 'Asia/Irkutsk', name: 'Irkutsk Time', city: 'Irkutsk', flag: '🇷🇺', offset: '+08:00', ianaTimezone: 'Asia/Irkutsk', abbreviation: 'IRKT' },
    { value: 'Asia/Istanbul', name: 'Turkey Time', city: 'Istanbul', flag: '🇹🇷', offset: '+03:00', ianaTimezone: 'Asia/Istanbul', abbreviation: 'TRT' },
    { value: 'Asia/Jakarta', name: 'Western Indonesian Time', city: 'Jakarta', flag: '🇮🇩', offset: '+07:00', ianaTimezone: 'Asia/Jakarta', abbreviation: 'WIB' },
    { value: 'Asia/Jayapura', name: 'Eastern Indonesian Time', city: 'Jayapura', flag: '🇮🇩', offset: '+09:00', ianaTimezone: 'Asia/Jayapura', abbreviation: 'WIT' },
    { value: 'Asia/Jerusalem', name: 'Israel Standard Time', city: 'Jerusalem', flag: '🇮🇱', offset: '+02:00', ianaTimezone: 'Asia/Jerusalem', abbreviation: 'IST' },
    { value: 'Asia/Kabul', name: 'Afghanistan Time', city: 'Kabul', flag: '🇦🇫', offset: '+04:30', ianaTimezone: 'Asia/Kabul', abbreviation: 'AFT' },
    { value: 'Asia/Kamchatka', name: 'Kamchatka Time', city: 'Petropavlovsk-Kamchatsky', flag: '🇷🇺', offset: '+12:00', ianaTimezone: 'Asia/Kamchatka', abbreviation: 'PETT' },
    { value: 'Asia/Karachi', name: 'Pakistan Standard Time', city: 'Karachi', flag: '🇵🇰', offset: '+05:00', ianaTimezone: 'Asia/Karachi', abbreviation: 'PKT' },
    { value: 'Asia/Kathmandu', name: 'Nepal Time', city: 'Kathmandu', flag: '🇳🇵', offset: '+05:45', ianaTimezone: 'Asia/Kathmandu', abbreviation: 'NPT' },
    { value: 'Asia/Khandyga', name: 'Yakutsk Time', city: 'Khandyga', flag: '🇷🇺', offset: '+09:00', ianaTimezone: 'Asia/Khandyga', abbreviation: 'YAKT' },
    { value: 'Asia/Kolkata', name: 'India Standard Time', city: 'Kolkata', flag: '🇮🇳', offset: '+05:30', ianaTimezone: 'Asia/Kolkata', abbreviation: 'IST' },
    { value: 'Asia/Krasnoyarsk', name: 'Krasnoyarsk Time', city: 'Krasnoyarsk', flag: '🇷🇺', offset: '+07:00', ianaTimezone: 'Asia/Krasnoyarsk', abbreviation: 'KRAT' },
    { value: 'Asia/Kuala_Lumpur', name: 'Malaysia Time', city: 'Kuala Lumpur', flag: '🇲🇾', offset: '+08:00', ianaTimezone: 'Asia/Kuala_Lumpur', abbreviation: 'MYT' },
    { value: 'Asia/Kuching', name: 'Malaysia Time', city: 'Kuching', flag: '🇲🇾', offset: '+08:00', ianaTimezone: 'Asia/Kuching', abbreviation: 'MYT' },
    { value: 'Asia/Kuwait', name: 'Arabia Standard Time', city: 'Kuwait City', flag: '🇰🇼', offset: '+03:00', ianaTimezone: 'Asia/Kuwait', abbreviation: 'AST' },
    { value: 'Asia/Macau', name: 'China Standard Time', city: 'Macau', flag: '🇲🇴', offset: '+08:00', ianaTimezone: 'Asia/Macau', abbreviation: 'CST' },
    { value: 'Asia/Magadan', name: 'Magadan Time', city: 'Magadan', flag: '🇷🇺', offset: '+11:00', ianaTimezone: 'Asia/Magadan', abbreviation: 'MAGT' },
    { value: 'Asia/Makassar', name: 'Central Indonesian Time', city: 'Makassar', flag: '🇮🇩', offset: '+08:00', ianaTimezone: 'Asia/Makassar', abbreviation: 'WITA' },
    { value: 'Asia/Manila', name: 'Philippine Standard Time', city: 'Manila', flag: '🇵🇭', offset: '+08:00', ianaTimezone: 'Asia/Manila', abbreviation: 'PHT' },
    { value: 'Asia/Muscat', name: 'Gulf Standard Time', city: 'Muscat', flag: '🇴🇲', offset: '+04:00', ianaTimezone: 'Asia/Muscat', abbreviation: 'GST' },
    { value: 'Asia/Nicosia', name: 'Eastern European Time', city: 'Nicosia', flag: '🇨🇾', offset: '+02:00', ianaTimezone: 'Asia/Nicosia', abbreviation: 'EET' },
    { value: 'Asia/Novokuznetsk', name: 'Krasnoyarsk Time', city: 'Novokuznetsk', flag: '🇷🇺', offset: '+07:00', ianaTimezone: 'Asia/Novokuznetsk', abbreviation: 'KRAT' },
    { value: 'Asia/Novosibirsk', name: 'Novosibirsk Time', city: 'Novosibirsk', flag: '🇷🇺', offset: '+07:00', ianaTimezone: 'Asia/Novosibirsk', abbreviation: 'NOVT' },
    { value: 'Asia/Omsk', name: 'Omsk Time', city: 'Omsk', flag: '🇷🇺', offset: '+06:00', ianaTimezone: 'Asia/Omsk', abbreviation: 'OMST' },
    { value: 'Asia/Oral', name: 'West Kazakhstan Time', city: 'Oral', flag: '🇰🇿', offset: '+05:00', ianaTimezone: 'Asia/Oral', abbreviation: 'WKT' },
    { value: 'Asia/Phnom_Penh', name: 'Indochina Time', city: 'Phnom Penh', flag: '🇰🇭', offset: '+07:00', ianaTimezone: 'Asia/Phnom_Penh', abbreviation: 'ICT' },
    { value: 'Asia/Pontianak', name: 'Western Indonesian Time', city: 'Pontianak', flag: '🇮🇩', offset: '+07:00', ianaTimezone: 'Asia/Pontianak', abbreviation: 'WIB' },
    { value: 'Asia/Pyongyang', name: 'Pyongyang Time', city: 'Pyongyang', flag: '🇰🇵', offset: '+09:00', ianaTimezone: 'Asia/Pyongyang', abbreviation: 'KST' },
    { value: 'Asia/Qatar', name: 'Arabia Standard Time', city: 'Doha', flag: '🇶🇦', offset: '+03:00', ianaTimezone: 'Asia/Qatar', abbreviation: 'AST' },
    { value: 'Asia/Qostanay', name: 'East Kazakhstan Time', city: 'Qostanay', flag: '🇰🇿', offset: '+06:00', ianaTimezone: 'Asia/Qostanay', abbreviation: 'EKT' },
    { value: 'Asia/Qyzylorda', name: 'East Kazakhstan Time', city: 'Qyzylorda', flag: '🇰🇿', offset: '+05:00', ianaTimezone: 'Asia/Qyzylorda', abbreviation: 'EKT' },
    { value: 'Asia/Riyadh', name: 'Arabia Standard Time', city: 'Riyadh', flag: '🇸🇦', offset: '+03:00', ianaTimezone: 'Asia/Riyadh', abbreviation: 'AST' },
    { value: 'Asia/Sakhalin', name: 'Sakhalin Time', city: 'Yuzhno-Sakhalinsk', flag: '🇷🇺', offset: '+11:00', ianaTimezone: 'Asia/Sakhalin', abbreviation: 'SAKT' },
    { value: 'Asia/Samarkand', name: 'Uzbekistan Time', city: 'Samarkand', flag: '🇺🇿', offset: '+05:00', ianaTimezone: 'Asia/Samarkand', abbreviation: 'UZT' },
    { value: 'Asia/Seoul', name: 'Korea Standard Time', city: 'Seoul', flag: '🇰🇷', offset: '+09:00', ianaTimezone: 'Asia/Seoul', abbreviation: 'KST' },
    { value: 'Asia/Shanghai', name: 'China Standard Time', city: 'Shanghai', flag: '🇨🇳', offset: '+08:00', ianaTimezone: 'Asia/Shanghai', abbreviation: 'CST' },
    { value: 'Asia/Singapore', name: 'Singapore Standard Time', city: 'Singapore', flag: '🇸🇬', offset: '+08:00', ianaTimezone: 'Asia/Singapore', abbreviation: 'SGT' },
    { value: 'Asia/Srednekolymsk', name: 'Srednekolymsk Time', city: 'Srednekolymsk', flag: '🇷🇺', offset: '+11:00', ianaTimezone: 'Asia/Srednekolymsk', abbreviation: 'SRET' },
    { value: 'Asia/Taipei', name: 'China Standard Time', city: 'Taipei', flag: '🇹🇼', offset: '+08:00', ianaTimezone: 'Asia/Taipei', abbreviation: 'CST' },
    { value: 'Asia/Tashkent', name: 'Uzbekistan Time', city: 'Tashkent', flag: '🇺🇿', offset: '+05:00', ianaTimezone: 'Asia/Tashkent', abbreviation: 'UZT' },
    { value: 'Asia/Tbilisi', name: 'Georgia Standard Time', city: 'Tbilisi', flag: '🇬🇪', offset: '+04:00', ianaTimezone: 'Asia/Tbilisi', abbreviation: 'GET' },
    { value: 'Asia/Tehran', name: 'Iran Standard Time', city: 'Tehran', flag: '🇮🇷', offset: '+03:30', ianaTimezone: 'Asia/Tehran', abbreviation: 'IRST' },
    { value: 'Asia/Thimphu', name: 'Bhutan Time', city: 'Thimphu', flag: '🇧🇹', offset: '+06:00', ianaTimezone: 'Asia/Thimphu', abbreviation: 'BTT' },
    { value: 'Asia/Tokyo', name: 'Japan Standard Time', city: 'Tokyo', flag: '🇯🇵', offset: '+09:00', ianaTimezone: 'Asia/Tokyo', abbreviation: 'JST' },
    { value: 'Asia/Tomsk', name: 'Tomsk Time', city: 'Tomsk', flag: '🇷🇺', offset: '+07:00', ianaTimezone: 'Asia/Tomsk', abbreviation: 'TSK' },
    { value: 'Asia/Ulaanbaatar', name: 'Ulaanbaatar Standard Time', city: 'Ulaanbaatar', flag: '🇲🇳', offset: '+08:00', ianaTimezone: 'Asia/Ulaanbaatar', abbreviation: 'ULAT' },
    { value: 'Asia/Urumqi', name: 'China Standard Time', city: 'Ürümqi', flag: '🇨🇳', offset: '+06:00', ianaTimezone: 'Asia/Urumqi', abbreviation: 'CST' },
    { value: 'Asia/Ust-Nera', name: 'Vladivostok Time', city: 'Ust-Nera', flag: '🇷🇺', offset: '+10:00', ianaTimezone: 'Asia/Ust-Nera', abbreviation: 'VLAT' },
    { value: 'Asia/Vientiane', name: 'Indochina Time', city: 'Vientiane', flag: '🇱🇦', offset: '+07:00', ianaTimezone: 'Asia/Vientiane', abbreviation: 'ICT' },
    { value: 'Asia/Vladivostok', name: 'Vladivostok Time', city: 'Vladivostok', flag: '🇷🇺', offset: '+10:00', ianaTimezone: 'Asia/Vladivostok', abbreviation: 'VLAT' },
    { value: 'Asia/Yakutsk', name: 'Yakutsk Time', city: 'Yakutsk', flag: '🇷🇺', offset: '+09:00', ianaTimezone: 'Asia/Yakutsk', abbreviation: 'YAKT' },
    { value: 'Asia/Yangon', name: 'Myanmar Time', city: 'Yangon', flag: '🇲🇲', offset: '+06:30', ianaTimezone: 'Asia/Yangon', abbreviation: 'MMT' },
    { value: 'Asia/Yekaterinburg', name: 'Yekaterinburg Time', city: 'Yekaterinburg', flag: '🇷🇺', offset: '+05:00', ianaTimezone: 'Asia/Yekaterinburg', abbreviation: 'YEKT' },
    { value: 'Asia/Yerevan', name: 'Armenia Time', city: 'Yerevan', flag: '🇦🇲', offset: '+04:00', ianaTimezone: 'Asia/Yerevan', abbreviation: 'AMT' },

    // Atlantic
    { value: 'Atlantic/Azores', name: 'Azores Standard Time', city: 'Ponta Delgada', flag: '🇵🇹', offset: '-01:00', ianaTimezone: 'Atlantic/Azores', abbreviation: 'AZOT' },
    { value: 'Atlantic/Bermuda', name: 'Atlantic Standard Time', city: 'Hamilton', flag: '🇧🇲', offset: '-04:00', ianaTimezone: 'Atlantic/Bermuda', abbreviation: 'AST' },
    { value: 'Atlantic/Canary', name: 'Western European Time', city: 'Las Palmas', flag: '🇪🇸', offset: '+00:00', ianaTimezone: 'Atlantic/Canary', abbreviation: 'WET' },
    { value: 'Atlantic/Cape_Verde', name: 'Cape Verde Time', city: 'Praia', flag: '🇨🇻', offset: '-01:00', ianaTimezone: 'Atlantic/Cape_Verde', abbreviation: 'CVT' },
    { value: 'Atlantic/Faroe', name: 'Western European Time', city: 'Tórshavn', flag: '🇫🇴', offset: '+00:00', ianaTimezone: 'Atlantic/Faroe', abbreviation: 'WET' },
    { value: 'Atlantic/Madeira', name: 'Western European Time', city: 'Funchal', flag: '🇵🇹', offset: '+00:00', ianaTimezone: 'Atlantic/Madeira', abbreviation: 'WET' },
    { value: 'Atlantic/Reykjavik', name: 'Greenwich Mean Time', city: 'Reykjavík', flag: '🇮🇸', offset: '+00:00', ianaTimezone: 'Atlantic/Reykjavik', abbreviation: 'GMT' },
    { value: 'Atlantic/South_Georgia', name: 'South Georgia Time', city: 'King Edward Point', flag: '🇬🇸', offset: '-02:00', ianaTimezone: 'Atlantic/South_Georgia', abbreviation: 'GST' },
    { value: 'Atlantic/St_Helena', name: 'Greenwich Mean Time', city: 'Jamestown', flag: '🇸🇭', offset: '+00:00', ianaTimezone: 'Atlantic/St_Helena', abbreviation: 'GMT' },
    { value: 'Atlantic/Stanley', name: 'Falkland Islands Time', city: 'Stanley', flag: '🇫🇰', offset: '-03:00', ianaTimezone: 'Atlantic/Stanley', abbreviation: 'FKT' },

    // Australia
    { value: 'Australia/Adelaide', name: 'Australian Central Standard Time', city: 'Adelaide', flag: '🇦🇺', offset: '+09:30', ianaTimezone: 'Australia/Adelaide', abbreviation: 'ACST' },
    { value: 'Australia/Brisbane', name: 'Australian Eastern Standard Time', city: 'Brisbane', flag: '🇦🇺', offset: '+10:00', ianaTimezone: 'Australia/Brisbane', abbreviation: 'AEST' },
    { value: 'Australia/Broken_Hill', name: 'Australian Central Standard Time', city: 'Broken Hill', flag: '🇦🇺', offset: '+09:30', ianaTimezone: 'Australia/Broken_Hill', abbreviation: 'ACST' },
    { value: 'Australia/Darwin', name: 'Australian Central Standard Time', city: 'Darwin', flag: '🇦🇺', offset: '+09:30', ianaTimezone: 'Australia/Darwin', abbreviation: 'ACST' },
    { value: 'Australia/Eucla', name: 'Australian Central Western Standard Time', city: 'Eucla', flag: '🇦🇺', offset: '+08:45', ianaTimezone: 'Australia/Eucla', abbreviation: 'ACWST' },
    { value: 'Australia/Hobart', name: 'Australian Eastern Standard Time', city: 'Hobart', flag: '🇦🇺', offset: '+10:00', ianaTimezone: 'Australia/Hobart', abbreviation: 'AEST' },
    { value: 'Australia/Lindeman', name: 'Australian Eastern Standard Time', city: 'Lindeman Island', flag: '🇦🇺', offset: '+10:00', ianaTimezone: 'Australia/Lindeman', abbreviation: 'AEST' },
    { value: 'Australia/Lord_Howe', name: 'Lord Howe Standard Time', city: 'Lord Howe Island', flag: '🇦🇺', offset: '+10:30', ianaTimezone: 'Australia/Lord_Howe', abbreviation: 'LHST' },
    { value: 'Australia/Melbourne', name: 'Australian Eastern Standard Time', city: 'Melbourne', flag: '🇦🇺', offset: '+10:00', ianaTimezone: 'Australia/Melbourne', abbreviation: 'AEST' },
    { value: 'Australia/Perth', name: 'Australian Western Standard Time', city: 'Perth', flag: '🇦🇺', offset: '+08:00', ianaTimezone: 'Australia/Perth', abbreviation: 'AWST' },
    { value: 'Australia/Sydney', name: 'Australian Eastern Standard Time', city: 'Sydney', flag: '🇦🇺', offset: '+10:00', ianaTimezone: 'Australia/Sydney', abbreviation: 'AEST' },

    // Europe
    { value: 'Europe/Amsterdam', name: 'Central European Time', city: 'Amsterdam', flag: '🇳🇱', offset: '+01:00', ianaTimezone: 'Europe/Amsterdam', abbreviation: 'CET' },
    { value: 'Europe/Andorra', name: 'Central European Time', city: 'Andorra la Vella', flag: '🇦🇩', offset: '+01:00', ianaTimezone: 'Europe/Andorra', abbreviation: 'CET' },
    { value: 'Europe/Astrakhan', name: 'Astrakhan Time', city: 'Astrakhan', flag: '🇷🇺', offset: '+04:00', ianaTimezone: 'Europe/Astrakhan', abbreviation: 'AST' },
    { value: 'Europe/Athens', name: 'Eastern European Time', city: 'Athens', flag: '🇬🇷', offset: '+02:00', ianaTimezone: 'Europe/Athens', abbreviation: 'EET' },
    { value: 'Europe/Belgrade', name: 'Central European Time', city: 'Belgrade', flag: '🇷🇸', offset: '+01:00', ianaTimezone: 'Europe/Belgrade', abbreviation: 'CET' },
    { value: 'Europe/Berlin', name: 'Central European Time', city: 'Berlin', flag: '🇩🇪', offset: '+01:00', ianaTimezone: 'Europe/Berlin', abbreviation: 'CET' },
    { value: 'Europe/Bratislava', name: 'Central European Time', city: 'Bratislava', flag: '🇸🇰', offset: '+01:00', ianaTimezone: 'Europe/Bratislava', abbreviation: 'CET' },
    { value: 'Europe/Brussels', name: 'Central European Time', city: 'Brussels', flag: '🇧🇪', offset: '+01:00', ianaTimezone: 'Europe/Brussels', abbreviation: 'CET' },
    { value: 'Europe/Bucharest', name: 'Eastern European Time', city: 'Bucharest', flag: '🇷🇴', offset: '+02:00', ianaTimezone: 'Europe/Bucharest', abbreviation: 'EET' },
    { value: 'Europe/Budapest', name: 'Central European Time', city: 'Budapest', flag: '🇭🇺', offset: '+01:00', ianaTimezone: 'Europe/Budapest', abbreviation: 'CET' },
    { value: 'Europe/Busingen', name: 'Central European Time', city: 'Büsingen am Hochrhein', flag: '🇩🇪', offset: '+01:00', ianaTimezone: 'Europe/Busingen', abbreviation: 'CET' },
    { value: 'Europe/Chisinau', name: 'Eastern European Time', city: 'Chișinău', flag: '🇲🇩', offset: '+02:00', ianaTimezone: 'Europe/Chisinau', abbreviation: 'EET' },
    { value: 'Europe/Copenhagen', name: 'Central European Time', city: 'Copenhagen', flag: '🇩🇰', offset: '+01:00', ianaTimezone: 'Europe/Copenhagen', abbreviation: 'CET' },
    { value: 'Europe/Dublin', name: 'Greenwich Mean Time', city: 'Dublin', flag: '🇮🇪', offset: '+00:00', ianaTimezone: 'Europe/Dublin', abbreviation: 'GMT' },
    { value: 'Europe/Gibraltar', name: 'Central European Time', city: 'Gibraltar', flag: '🇬🇮', offset: '+01:00', ianaTimezone: 'Europe/Gibraltar', abbreviation: 'CET' },
    { value: 'Europe/Guernsey', name: 'Greenwich Mean Time', city: 'St. Peter Port', flag: '🇬🇬', offset: '+00:00', ianaTimezone: 'Europe/Guernsey', abbreviation: 'GMT' },
    { value: 'Europe/Helsinki', name: 'Eastern European Time', city: 'Helsinki', flag: '🇫🇮', offset: '+02:00', ianaTimezone: 'Europe/Helsinki', abbreviation: 'EET' },
    { value: 'Europe/Isle_of_Man', name: 'Greenwich Mean Time', city: 'Douglas', flag: '🇮🇲', offset: '+00:00', ianaTimezone: 'Europe/Isle_of_Man', abbreviation: 'GMT' },
    { value: 'Europe/Istanbul', name: 'Turkey Time', city: 'Istanbul', flag: '🇹🇷', offset: '+03:00', ianaTimezone: 'Europe/Istanbul', abbreviation: 'TRT' },
    { value: 'Europe/Jersey', name: 'Greenwich Mean Time', city: 'Saint Helier', flag: '🇯🇪', offset: '+00:00', ianaTimezone: 'Europe/Jersey', abbreviation: 'GMT' },
    { value: 'Europe/Kaliningrad', name: 'Eastern European Time', city: 'Kaliningrad', flag: '🇷🇺', offset: '+02:00', ianaTimezone: 'Europe/Kaliningrad', abbreviation: 'EET' },
    { value: 'Europe/Kiev', name: 'Eastern European Time', city: 'Kiev', flag: '🇺🇦', offset: '+02:00', ianaTimezone: 'Europe/Kiev', abbreviation: 'EET' },
    { value: 'Europe/Kirov', name: 'Moscow Time', city: 'Kirov', flag: '🇷🇺', offset: '+03:00', ianaTimezone: 'Europe/Kirov', abbreviation: 'MSK' },
    { value: 'Europe/Lisbon', name: 'Western European Time', city: 'Lisbon', flag: '🇵🇹', offset: '+00:00', ianaTimezone: 'Europe/Lisbon', abbreviation: 'WET' },
    { value: 'Europe/Ljubljana', name: 'Central European Time', city: 'Ljubljana', flag: '🇸🇮', offset: '+01:00', ianaTimezone: 'Europe/Ljubljana', abbreviation: 'CET' },
    { value: 'Europe/London', name: 'Greenwich Mean Time', city: 'London', flag: '🇬🇧', offset: '+00:00', ianaTimezone: 'Europe/London', abbreviation: 'GMT' },
    { value: 'Europe/Luxembourg', name: 'Central European Time', city: 'Luxembourg', flag: '🇱🇺', offset: '+01:00', ianaTimezone: 'Europe/Luxembourg', abbreviation: 'CET' },
    { value: 'Europe/Madrid', name: 'Central European Time', city: 'Madrid', flag: '🇪🇸', offset: '+01:00', ianaTimezone: 'Europe/Madrid', abbreviation: 'CET' },
    { value: 'Europe/Malta', name: 'Central European Time', city: 'Valletta', flag: '🇲🇹', offset: '+01:00', ianaTimezone: 'Europe/Malta', abbreviation: 'CET' },
    { value: 'Europe/Mariehamn', name: 'Eastern European Time', city: 'Mariehamn', flag: '🇦🇽', offset: '+02:00', ianaTimezone: 'Europe/Mariehamn', abbreviation: 'EET' },
    { value: 'Europe/Minsk', name: 'Moscow Time', city: 'Minsk', flag: '🇧🇾', offset: '+03:00', ianaTimezone: 'Europe/Minsk', abbreviation: 'MSK' },
    { value: 'Europe/Monaco', name: 'Central European Time', city: 'Monaco', flag: '🇲🇨', offset: '+01:00', ianaTimezone: 'Europe/Monaco', abbreviation: 'CET' },
    { value: 'Europe/Moscow', name: 'Moscow Time', city: 'Moscow', flag: '🇷🇺', offset: '+03:00', ianaTimezone: 'Europe/Moscow', abbreviation: 'MSK' },
    { value: 'Europe/Oslo', name: 'Central European Time', city: 'Oslo', flag: '🇳🇴', offset: '+01:00', ianaTimezone: 'Europe/Oslo', abbreviation: 'CET' },
    { value: 'Europe/Paris', name: 'Central European Time', city: 'Paris', flag: '🇫🇷', offset: '+01:00', ianaTimezone: 'Europe/Paris', abbreviation: 'CET' },
    { value: 'Europe/Podgorica', name: 'Central European Time', city: 'Podgorica', flag: '🇲🇪', offset: '+01:00', ianaTimezone: 'Europe/Podgorica', abbreviation: 'CET' },
    { value: 'Europe/Prague', name: 'Central European Time', city: 'Prague', flag: '🇨🇿', offset: '+01:00', ianaTimezone: 'Europe/Prague', abbreviation: 'CET' },
    { value: 'Europe/Riga', name: 'Eastern European Time', city: 'Riga', flag: '🇱🇻', offset: '+02:00', ianaTimezone: 'Europe/Riga', abbreviation: 'EET' },
    { value: 'Europe/Rome', name: 'Central European Time', city: 'Rome', flag: '🇮🇹', offset: '+01:00', ianaTimezone: 'Europe/Rome', abbreviation: 'CET' },
    { value: 'Europe/Samara', name: 'Samara Time', city: 'Samara', flag: '🇷🇺', offset: '+04:00', ianaTimezone: 'Europe/Samara', abbreviation: 'SAMT' },
    { value: 'Europe/San_Marino', name: 'Central European Time', city: 'San Marino', flag: '🇸🇲', offset: '+01:00', ianaTimezone: 'Europe/San_Marino', abbreviation: 'CET' },
    { value: 'Europe/Sarajevo', name: 'Central European Time', city: 'Sarajevo', flag: '🇧🇦', offset: '+01:00', ianaTimezone: 'Europe/Sarajevo', abbreviation: 'CET' },
    { value: 'Europe/Saratov', name: 'Saratov Time', city: 'Saratov', flag: '🇷🇺', offset: '+04:00', ianaTimezone: 'Europe/Saratov', abbreviation: 'SRT' },
    { value: 'Europe/Simferopol', name: 'Moscow Time', city: 'Simferopol', flag: '🇺🇦', offset: '+03:00', ianaTimezone: 'Europe/Simferopol', abbreviation: 'MSK' },
    { value: 'Europe/Skopje', name: 'Central European Time', city: 'Skopje', flag: '🇲🇰', offset: '+01:00', ianaTimezone: 'Europe/Skopje', abbreviation: 'CET' },
    { value: 'Europe/Sofia', name: 'Eastern European Time', city: 'Sofia', flag: '🇧🇬', offset: '+02:00', ianaTimezone: 'Europe/Sofia', abbreviation: 'EET' },
    { value: 'Europe/Stockholm', name: 'Central European Time', city: 'Stockholm', flag: '🇸🇪', offset: '+01:00', ianaTimezone: 'Europe/Stockholm', abbreviation: 'CET' },
    { value: 'Europe/Tallinn', name: 'Eastern European Time', city: 'Tallinn', flag: '🇪🇪', offset: '+02:00', ianaTimezone: 'Europe/Tallinn', abbreviation: 'EET' },
    { value: 'Europe/Tirane', name: 'Central European Time', city: 'Tirana', flag: '🇦🇱', offset: '+01:00', ianaTimezone: 'Europe/Tirane', abbreviation: 'CET' },
    { value: 'Europe/Ulyanovsk', name: 'Ulyanovsk Time', city: 'Ulyanovsk', flag: '🇷🇺', offset: '+04:00', ianaTimezone: 'Europe/Ulyanovsk', abbreviation: 'ULT' },
    { value: 'Europe/Uzhgorod', name: 'Eastern European Time', city: 'Uzhhorod', flag: '🇺🇦', offset: '+02:00', ianaTimezone: 'Europe/Uzhgorod', abbreviation: 'EET' },
    { value: 'Europe/Vaduz', name: 'Central European Time', city: 'Vaduz', flag: '🇱🇮', offset: '+01:00', ianaTimezone: 'Europe/Vaduz', abbreviation: 'CET' },
    { value: 'Europe/Vatican', name: 'Central European Time', city: 'Vatican City', flag: '🇻🇦', offset: '+01:00', ianaTimezone: 'Europe/Vatican', abbreviation: 'CET' },
    { value: 'Europe/Vienna', name: 'Central European Time', city: 'Vienna', flag: '🇦🇹', offset: '+01:00', ianaTimezone: 'Europe/Vienna', abbreviation: 'CET' },
    { value: 'Europe/Vilnius', name: 'Eastern European Time', city: 'Vilnius', flag: '🇱🇹', offset: '+02:00', ianaTimezone: 'Europe/Vilnius', abbreviation: 'EET' },
    { value: 'Europe/Volgograd', name: 'Volgograd Time', city: 'Volgograd', flag: '🇷🇺', offset: '+04:00', ianaTimezone: 'Europe/Volgograd', abbreviation: 'VGT' },
    { value: 'Europe/Warsaw', name: 'Central European Time', city: 'Warsaw', flag: '🇵🇱', offset: '+01:00', ianaTimezone: 'Europe/Warsaw', abbreviation: 'CET' },
    { value: 'Europe/Zagreb', name: 'Central European Time', city: 'Zagreb', flag: '🇭🇷', offset: '+01:00', ianaTimezone: 'Europe/Zagreb', abbreviation: 'CET' },
    { value: 'Europe/Zaporozhye', name: 'Eastern European Time', city: 'Zaporizhzhia', flag: '🇺🇦', offset: '+02:00', ianaTimezone: 'Europe/Zaporozhye', abbreviation: 'EET' },
    { value: 'Europe/Zurich', name: 'Central European Time', city: 'Zurich', flag: '🇨🇭', offset: '+01:00', ianaTimezone: 'Europe/Zurich', abbreviation: 'CET' },

    // Indian Ocean
    { value: 'Indian/Antananarivo', name: 'East Africa Time', city: 'Antananarivo', flag: '🇲🇬', offset: '+03:00', ianaTimezone: 'Indian/Antananarivo', abbreviation: 'EAT' },
    { value: 'Indian/Chagos', name: 'Indian Ocean Time', city: 'Diego Garcia', flag: '🇮🇴', offset: '+06:00', ianaTimezone: 'Indian/Chagos', abbreviation: 'IOT' },
    { value: 'Indian/Christmas', name: 'Christmas Island Time', city: 'Flying Fish Cove', flag: '🇨🇽', offset: '+07:00', ianaTimezone: 'Indian/Christmas', abbreviation: 'CXT' },
    { value: 'Indian/Cocos', name: 'Cocos Islands Time', city: 'West Island', flag: '🇨🇨', offset: '+06:30', ianaTimezone: 'Indian/Cocos', abbreviation: 'CCT' },
    { value: 'Indian/Comoro', name: 'East Africa Time', city: 'Moroni', flag: '🇰🇲', offset: '+03:00', ianaTimezone: 'Indian/Comoro', abbreviation: 'EAT' },
    { value: 'Indian/Kerguelen', name: 'French Southern & Antarctic Time', city: 'Port-aux-Français', flag: '🇹🇫', offset: '+05:00', ianaTimezone: 'Indian/Kerguelen', abbreviation: 'TFT' },
    { value: 'Indian/Mahe', name: 'Seychelles Time', city: 'Victoria', flag: '🇸🇨', offset: '+04:00', ianaTimezone: 'Indian/Mahe', abbreviation: 'SCT' },
    { value: 'Indian/Maldives', name: 'Maldives Time', city: 'Malé', flag: '🇲🇻', offset: '+05:00', ianaTimezone: 'Indian/Maldives', abbreviation: 'MVT' },
    { value: 'Indian/Mauritius', name: 'Mauritius Time', city: 'Port Louis', flag: '🇲🇺', offset: '+04:00', ianaTimezone: 'Indian/Mauritius', abbreviation: 'MUT' },
    { value: 'Indian/Mayotte', name: 'East Africa Time', city: 'Mamoudzou', flag: '🇾🇹', offset: '+03:00', ianaTimezone: 'Indian/Mayotte', abbreviation: 'EAT' },
    { value: 'Indian/Reunion', name: 'Réunion Time', city: 'Saint-Denis', flag: '🇷🇪', offset: '+04:00', ianaTimezone: 'Indian/Reunion', abbreviation: 'RET' },

    // Pacific
    { value: 'Pacific/Apia', name: 'Samoa Standard Time', city: 'Apia', flag: '🇼🇸', offset: '+13:00', ianaTimezone: 'Pacific/Apia', abbreviation: 'SST' },
    { value: 'Pacific/Auckland', name: 'New Zealand Standard Time', city: 'Auckland', flag: '🇳🇿', offset: '+12:00', ianaTimezone: 'Pacific/Auckland', abbreviation: 'NZST' },
    { value: 'Pacific/Bougainville', name: 'Bougainville Standard Time', city: 'Buka', flag: '🇵🇬', offset: '+11:00', ianaTimezone: 'Pacific/Bougainville', abbreviation: 'BST' },
    { value: 'Pacific/Chatham', name: 'Chatham Standard Time', city: 'Waitangi', flag: '🇳🇿', offset: '+12:45', ianaTimezone: 'Pacific/Chatham', abbreviation: 'CHAST' },
    { value: 'Pacific/Chuuk', name: 'Chuuk Time', city: 'Weno', flag: '🇫🇲', offset: '+10:00', ianaTimezone: 'Pacific/Chuuk', abbreviation: 'CHUT' },
    { value: 'Pacific/Easter', name: 'Easter Island Standard Time', city: 'Hanga Roa', flag: '🇨🇱', offset: '-06:00', ianaTimezone: 'Pacific/Easter', abbreviation: 'EAST' },
    { value: 'Pacific/Efate', name: 'Vanuatu Time', city: 'Port Vila', flag: '🇻🇺', offset: '+11:00', ianaTimezone: 'Pacific/Efate', abbreviation: 'VUT' },
    { value: 'Pacific/Fakaofo', name: 'Tokelau Time', city: 'Fakaofo', flag: '🇹🇰', offset: '+13:00', ianaTimezone: 'Pacific/Fakaofo', abbreviation: 'TKT' },
    { value: 'Pacific/Fiji', name: 'Fiji Time', city: 'Suva', flag: '🇫🇯', offset: '+12:00', ianaTimezone: 'Pacific/Fiji', abbreviation: 'FJT' },
    { value: 'Pacific/Funafuti', name: 'Tuvalu Time', city: 'Funafuti', flag: '🇹🇻', offset: '+12:00', ianaTimezone: 'Pacific/Funafuti', abbreviation: 'TVT' },
    { value: 'Pacific/Galapagos', name: 'Galápagos Time', city: 'Puerto Baquerizo Moreno', flag: '🇪🇨', offset: '-06:00', ianaTimezone: 'Pacific/Galapagos', abbreviation: 'GALT' },
    { value: 'Pacific/Gambier', name: 'Gambier Time', city: 'Rikitea', flag: '🇵🇫', offset: '-09:00', ianaTimezone: 'Pacific/Gambier', abbreviation: 'GAMT' },
    { value: 'Pacific/Guadalcanal', name: 'Solomon Islands Time', city: 'Honiara', flag: '🇸🇧', offset: '+11:00', ianaTimezone: 'Pacific/Guadalcanal', abbreviation: 'SBT' },
    { value: 'Pacific/Guam', name: 'Chamorro Standard Time', city: 'Hagåtña', flag: '🇬🇺', offset: '+10:00', ianaTimezone: 'Pacific/Guam', abbreviation: 'ChST' },
    { value: 'Pacific/Honolulu', name: 'Hawaii-Aleutian Standard Time', city: 'Honolulu', flag: '🇺🇸', offset: '-10:00', ianaTimezone: 'Pacific/Honolulu', abbreviation: 'HST' },
    { value: 'Pacific/Kanton', name: 'Phoenix Islands Time', city: 'Kanton', flag: '🇰🇮', offset: '+13:00', ianaTimezone: 'Pacific/Kanton', abbreviation: 'PHOT' },
    { value: 'Pacific/Kiritimati', name: 'Line Islands Time', city: 'Kiritimati', flag: '🇰🇮', offset: '+14:00', ianaTimezone: 'Pacific/Kiritimati', abbreviation: 'LINT' },
    { value: 'Pacific/Kosrae', name: 'Kosrae Time', city: 'Tofol', flag: '🇫🇲', offset: '+11:00', ianaTimezone: 'Pacific/Kosrae', abbreviation: 'KOST' },
    { value: 'Pacific/Kwajalein', name: 'Marshall Islands Time', city: 'Kwajalein', flag: '🇲🇭', offset: '+12:00', ianaTimezone: 'Pacific/Kwajalein', abbreviation: 'MHT' },
    { value: 'Pacific/Majuro', name: 'Marshall Islands Time', city: 'Majuro', flag: '🇲🇭', offset: '+12:00', ianaTimezone: 'Pacific/Majuro', abbreviation: 'MHT' },
    { value: 'Pacific/Marquesas', name: 'Marquesas Time', city: 'Taiohae', flag: '🇵🇫', offset: '-09:30', ianaTimezone: 'Pacific/Marquesas', abbreviation: 'MART' },
    { value: 'Pacific/Midway', name: 'Samoa Standard Time', city: 'Midway Atoll', flag: '🇺🇲', offset: '-11:00', ianaTimezone: 'Pacific/Midway', abbreviation: 'SST' },
    { value: 'Pacific/Nauru', name: 'Nauru Time', city: 'Yaren', flag: '🇳🇷', offset: '+12:00', ianaTimezone: 'Pacific/Nauru', abbreviation: 'NRT' },
    { value: 'Pacific/Niue', name: 'Niue Time', city: 'Alofi', flag: '🇳🇺', offset: '-11:00', ianaTimezone: 'Pacific/Niue', abbreviation: 'NUT' },
    { value: 'Pacific/Norfolk', name: 'Norfolk Island Time', city: 'Kingston', flag: '🇳🇫', offset: '+11:00', ianaTimezone: 'Pacific/Norfolk', abbreviation: 'NFT' },
    { value: 'Pacific/Noumea', name: 'New Caledonia Time', city: 'Nouméa', flag: '🇳🇨', offset: '+11:00', ianaTimezone: 'Pacific/Noumea', abbreviation: 'NCT' },
    { value: 'Pacific/Pago_Pago', name: 'Samoa Standard Time', city: 'Pago Pago', flag: '🇦🇸', offset: '-11:00', ianaTimezone: 'Pacific/Pago_Pago', abbreviation: 'SST' },
    { value: 'Pacific/Palau', name: 'Palau Time', city: 'Ngerulmud', flag: '🇵🇼', offset: '+09:00', ianaTimezone: 'Pacific/Palau', abbreviation: 'PWT' },
    { value: 'Pacific/Pitcairn', name: 'Pitcairn Standard Time', city: 'Adamstown', flag: '🇵🇳', offset: '-08:00', ianaTimezone: 'Pacific/Pitcairn', abbreviation: 'PST' },
    { value: 'Pacific/Pohnpei', name: 'Pohnpei Standard Time', city: 'Palikir', flag: '🇫🇲', offset: '+11:00', ianaTimezone: 'Pacific/Pohnpei', abbreviation: 'PONT' },
    { value: 'Pacific/Port_Moresby', name: 'Papua New Guinea Time', city: 'Port Moresby', flag: '🇵🇬', offset: '+10:00', ianaTimezone: 'Pacific/Port_Moresby', abbreviation: 'PGT' },
    { value: 'Pacific/Rarotonga', name: 'Cook Islands Time', city: 'Avarua', flag: '🇨🇰', offset: '-10:00', ianaTimezone: 'Pacific/Rarotonga', abbreviation: 'CKT' },
    { value: 'Pacific/Saipan', name: 'Chamorro Standard Time', city: 'Saipan', flag: '🇲🇵', offset: '+10:00', ianaTimezone: 'Pacific/Saipan', abbreviation: 'ChST' },
    { value: 'Pacific/Tahiti', name: 'Tahiti Time', city: 'Papeete', flag: '🇵🇫', offset: '-10:00', ianaTimezone: 'Pacific/Tahiti', abbreviation: 'TAHT' },
    { value: 'Pacific/Tarawa', name: 'Gilbert Islands Time', city: 'South Tarawa', flag: '🇰🇮', offset: '+12:00', ianaTimezone: 'Pacific/Tarawa', abbreviation: 'GILT' },
    { value: 'Pacific/Tongatapu', name: 'Tonga Time', city: 'Nuku\'alofa', flag: '🇹🇴', offset: '+13:00', ianaTimezone: 'Pacific/Tongatapu', abbreviation: 'TOT' },
    { value: 'Pacific/Wake', name: 'Wake Island Time', city: 'Wake Island', flag: '🇺🇲', offset: '+12:00', ianaTimezone: 'Pacific/Wake', abbreviation: 'WAKT' },
    { value: 'Pacific/Wallis', name: 'Wallis & Futuna Time', city: 'Mata-Utu', flag: '🇼🇫', offset: '+12:00', ianaTimezone: 'Pacific/Wallis', abbreviation: 'WFT' }
  ];

  // Add label property for backward compatibility
  return timezones.map(tz => ({
    ...tz,
    label: `${tz.abbreviation} - ${tz.name} (${tz.offset})`
  }));
}

// Export for use in other files
if (typeof window !== 'undefined') {
  window.getAllTimezones = getAllTimezones;
}

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = { getAllTimezones };
}
